language: node_js
node_js: stable
sudo: false
services: 
  - mongodb

before_install:
  - npm install

before_script: 
  - sleep 5
  - mongo sljTest --eval 'db.createCollection("usergenerates");'
  - mongo sljTest --eval 'db.usergenerates.save({_id:"User", next:1});'
  - mongo sljTest --eval 'db.createCollection("articlegenerates")'
  - mongo sljTest --eval 'db.articlegenerates.save({_id:"Article", next:1});'
  - mongo sljTest --eval 'db.createCollection("commentgenerates")'
  - mongo sljTest --eval 'db.commentgenerates.save({_id:"Comment", next:1});'

script:
  - npm run test

after_script:
  - npm run report
  - npm run coverage